os:
    - linux
    - osx

language: go

go:
    - tip

install: true

script:
    - make deps
    - gx-go rewrite
    - go get github.com/mattn/goveralls
    - goveralls -service=travis-ci

cache:
    directories:
        - $GOPATH/src/gx
